### ISSUE TITLE
Getting greyscale image for rendering in blender?

### ISSUE THREAD

**Issue by pootle** [GBillotey/Fractalshades#106] opened 2022-08-13 23:42 UTC
I see mention of using an output file as a DEM to use as input to blender, but there are no examples showing how to do this and 
I can't see how to use Disp_layer to get a 32bit image file to use in blender.

I did try loading the stop_iter.arr file, but could not see how to map the long array to a 2d image

**Comment by GBillotey** [comment] 2022-08-16 20:22
Hi,
Thanks for your feedback @pootle , and for using fractalshades 
It is indeed possible (with a "Disp_layer") and the documentation shall be improved.
I attach an example that shall run under 0.5.6 - much appreciated if you can confirm it works as intended !

[06-seahorse_interior-BLENDER_export .txt](https://github.com/GBillotey/Fractalshades/files/9354437/06-seahorse_interior-BLENDER_export.txt)

I will not close this issue when :

- the documentation is updated with an example
-  I noticed a bug where is is not possible to apply a mask to a Dip_layer ; the workaround is to apply the mask in Blender but this shall also be corrected.

**Comment by GBillotey** [comment] 2022-08-16 20:24
Typical use case:
![scenery6](https://user-images.githubusercontent.com/2669128/184978199-0ba1045a-eaf4-42f1-a90d-d66cd6a37826.jpg)

**Comment by GBillotey** [comment] 2022-12-17 13:59
Option added to GUI template function `fractalshades.gui.guitemplates.std_zooming` in v1.0.0
(see "additional outputs" parameters subsection)

**Comment by GBillotey** [comment] 2022-12-17 14:00
Xref #107

**Closed by GBillotey** 2022-12-17 14:00 UTC
Labels: bug, documentation
