### ISSUE TITLE
No result + no reaction of computer

### ISSUE THREAD

**Issue by Micro-fractal** [GBillotey/Fractalshades#120] opened 2022-12-20 20:18 UTC
I have installed Fractalshades 1.0.1 on my computer.
I have exported a Python script from the Fractalshades GUI (see attachment, Stopped.py) and disabled the Newton calculation, because the center of the fractal is already known. The reference orbit has a length of 500 million. After approx. 3h of computing time, the program closes unexpectedly without any result. See attachment, Stopped.png. After reopening the program, it said that the orbit was calculated and the calculation of the image would begin. But then my computer froze. After 3-5 minutes the program stopped, again.
I believe this is unintentional and would appreciate further investigation.

[Stopped.zip](https://github.com/GBillotey/Fractalshades/files/10272098/Stopped.zip)

PS: The logfile’s name is misspelled, it has a typo: It says “factalshades” instead of “fractalshades”.

**Comment by GBillotey** [comment] 2022-12-21 20:08
Thanks for the detailed report.
I will have a look but first thoughts, this could be either a segfault similar to #119 or, a caused by RAM limitation of the system (500 millions is admittedly, a large orbit - I expect it to be around 8 Go in RAM)

**Comment by GBillotey** [comment] 2022-12-23 18:10
On further investigation this looks rather like a RAM limitation. RAM peak usage is currently x5 the orbit as stored in double precision format. This calculation would probably need a system with 48 Go RAM installed - not tested.
Flagging this as Enhancement with the targets:

-  to lower RAM use in this case
-  to add a warning if a risk of crash is identified (based on system RAM and max iteration requested)

**Comment by GBillotey** [comment] 2023-04-02 14:52
RAM use for this test case is now below 16 Go. One has to desactivate both ``interior_detect`` and ``calc_dzndc``. Further improvement would be to double-check if storing the reference orbit in float32 format is enough ; this might push the computable orbit limit on a sytem with 16 Go RAM to 1 billion (1 000 000 000).

[Issue_120.zip](https://github.com/GBillotey/Fractalshades/files/11132523/Issue_120.zip)

**Comment by GBillotey** [comment] 2023-04-02 14:52
I will close this issue once #133 is merged.

**Closed** 2023-06-19 19:43 UTC
Labels: enhancement
